name: Code Climate Coverage Action

on: 
  push:
    branches: 
    - development
  pull_request:
    branches: 
    - development

jobs:
  test:
    name: running front end tests
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        node-version: [8, 10, 12]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: development
      - run: npm install -g yarn
      - run: yarn install
      - uses: paambaati/codeclimate-action@v2.4.0
        with:
          coverageCommand: yarn coverage
          debug: false 
    
 
