name: Code Climate Coverage Action

on: 
  push:
    branches: 
    - development
    paths:
      - app/*
  pull_request:
    branches: 
    - development
    paths:
      - app/*

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: paambaati/codeclimate-action@v2.4.0
        with:
          coverageCommand: yarn coverage
          debug: false 
    
 
