name: Code Climate Coverage Action

on: 
  push:
    branches: 
    - development
  pull_request:
    branches: 
    - development

jobs:
  test:
    name: running front end tests
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn test
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g yarn
      - run: yarn install
      - uses: paambaati/codeclimate-action@v2.4.0
        with:
          coverageCommand: yarn coverage
          debug: false 
    
 
